### ISSUE TITLE
Support for 2.10 GWT

### ISSUE THREAD

**Issue by rbernadev** [keinhaar/gwt-eclipse-plugin#1]
Hi ,
i tried the plugin with eclipse 2022-09 and it work with 2.8.2 and 2.9 gwt but not work with 2.10
Can you add support for 2.10 gwt version?

Thanks

Riccardo

**Comment by keinhaar** [comment]
@rbernadev 
Could you explain what is not working? Because even the original versions work for gwt 2.10 for me.

**Comment by rbernadev** [comment]
HI @keinhaar , thanks for response;
with my eclipse only on v 2.10 gwt i cant see  in run configuration gwt  the superdevelopment mode but only legacy mode. I can't run the project.
I have no problem with minor version of gwt 

Riccardo

**Comment by keinhaar** [comment]
Hi @rbernadev ,
sorry, but i dont get it. Just fresh installed eclipse 2022-09 and added my gwt-plugin version, and set gwt 2.10 as default. then i created an GWT Project and started it by using Right-Click -> Run As -> GWT Development Mode with Jetty. Everything works like expected.

**Comment by keinhaar** [comment]
A new official Plugin has been released.
